#!/bin/bash

echo "Installing utilities..."
sudo apt update

sudo apt install -y brightnessctl feh curl git alacritty zsh rofi
sudo apt install -y build-essential gcc g++ make cmake gdb ansible
sudo apt install -y flameshot libreadline-dev xclip
sudo apt install -y pulseaudio


echo "Setting up Oh My Zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Setting up fzf (fuzzy finder)..."
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

~/.fzf/install

echo "install ripgrep"
curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep_14.1.1-1_amd64.deb
sudo dpkg -i ripgrep_14.1.1-1_amd64.deb
rm ripgrep_14.1.1-1_amd64.deb
