local ok, harpoon = pcall(require, "harpoon")
if not ok then return end

harpoon:setup({})

vim.keymap.set("n", "<leader>ha", function() harpoon:list():add() end)
vim.keymap.set("n", "<leader>hm", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)
vim.keymap.set("n", "<leader>h1", function() harpoon:list():select(1) end)
vim.keymap.set("n", "<leader>h2", function() harpoon:list():select(2) end)
vim.keymap.set("n", "<leader>h3", function() harpoon:list():select(3) end)
vim.keymap.set("n", "<leader>h4", function() harpoon:list():select(4) end)
vim.keymap.set("n", "<leader>hn", function() harpoon:list():next() end)
vim.keymap.set("n", "<leader>hp", function() harpoon:list():prev() end)
vim.keymap.set("n", "<leader>hr1", function() harpoon:list():replace_at(1) end)
vim.keymap.set("n", "<leader>hr2", function() harpoon:list():replace_at(2) end)
vim.keymap.set("n", "<leader>hr3", function() harpoon:list():replace_at(3) end)
vim.keymap.set("n", "<leader>hr4", function() harpoon:list():replace_at(4) end)
vim.keymap.set("n", "<leader>hc1", function() harpoon:list():remove_at(1) end)
vim.keymap.set("n", "<leader>hc2", function() harpoon:list():remove_at(2) end)
vim.keymap.set("n", "<leader>hc3", function() harpoon:list():remove_at(3) end)
vim.keymap.set("n", "<leader>hc4", function() harpoon:list():remove_at(4) end)
vim.keymap.set("n", "<leader>hcx", function() harpoon:list():clear() end)
